### ISSUE TITLE
Adaptive Questionnaire + Platform configurator = Make sure they work

### ISSUE THREAD

**Issue by kostasgrevenitis** [c0c0n3/kitt4sme.live#454]

**Comment by pmpoukli** [comment]
Please make sure the API calls to RAMP are according to the spec. I attach it also here.


[Minimized API Call and new endpoints.pdf](https://github.com/c0c0n3/kitt4sme.live/files/14886548/Minimized.API.Call.and.new.endpoints.pdf)

**Comment by pmpoukli** [comment]
Tested today's version and looks like it works fine.
Please test again on future updates.
When going to RAMP (after 'find a kit for your needs) you should see something like the following image 

![Image](https://github.com/c0c0n3/kitt4sme.live/assets/19283281/1675d070-838e-4838-8472-9c96ae671c43)

**Comment by vcutrona** [comment]
I confirm that the API request POST /kits is the only one used by PC.
The API is invoked by passing the following path parameters:

- 'sid': a valid UUID
- 'user': the email of the user
- 'apikey': the RAMP API key

The request has a payload containing an object of type KitSetDTO, which is documented [here](https://platform-configurator.kitt4sme.collab-cloud.eu/docs#/kits/handle_kits_request_redirect_kits_ramp_get).
The KitSetDTO adheres to the structure reported in the PDF (some fields are not very clear, e.g., the content of the `kits[].tools[].dependencies` field is not specified).

We already tested the information flow 5 times.
If future updates are foreseen, please notify the required adjustments.

**Comment by karikolehmainen** [comment]
I ran the AQ again and run into an issue within the AQ. This is the questions and answers I used plus the resuting error log:
`Which of the following items, related to the manufacturing production, require to be improved?
- Automated processes (machines and robots activities)
- Manual processes (operators activities)

Which of the following aspects, related to the operators, require to be improved?
- Level of mental effort

Are quality inspections conducted manually or through an automated system?
- Manually

Which of the following machine-related problems impact on the performance of production?
- Critical setup of the machine
- Lack of sensors for data collection
- Lack of warning systems

In the performance evaluation process, what are the data-analysis related problems?
- Lack of enough data for a meaningful analysis
- Lack of predictive approach

Which of the following aspects are the most critical to be managed for the quality inspection system?
- Calibration or maintenance of inspection
- Data collection

Which of the following items cause mental stress?
- Variability of tasks based on the set of production condition (multitasking)
- Mental Strenuous Activities (Precision goes beyond human capabilities)

Do the set-up cause any of these problems?
- Scraps production

Which of the following challenges prevent an effective answer to the market demand?
- Job rotation difficult

In the performance evaluation process, what are the data-collection related problems?
- Time lost for manual collection
- Fragmented data collection

Which are the performance indicators that could be improved?
- Throughput rate
- Cycle time

Which of the following items cause physical disconfort or pain?
- Exposure to hazardous materials, noise, extreme temperatures and vibrations

How do you manage the training of operators placed in the production department?
- Knowledge is gained through long time experience

Which of the following human-related problems impact on the performance of production?
- Human machine interaction

--> ERROR


256 2024-05-16 07:34:15.614 ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentExcep>
255 java.lang.IllegalArgumentException: Cannot load status: no model for token=65c32627-6619-4fa0-80f0-e4b55be4dfaa
254     at ch.idsia.adaptive.backend.services.SurveyManagerService.lambda$getSurvey$1(SurveyManagerService.java:104)
253     at java.base/java.util.Optional.orElseThrow(Optional.java:403)
252     at ch.idsia.adaptive.backend.services.SurveyManagerService.getSurvey(SurveyManagerService.java:104)
251     at ch.idsia.adaptive.backend.services.SurveyManagerService.isFinished(SurveyManagerService.java:112)
250     at ch.idsia.adaptive.backend.controller.SurveyController.nextQuestion(SurveyController.java:334)
`

**Comment by karikolehmainen** [comment]
Possibly this is either browser based problem or timeout because error was produced wiuth Chrome and took a while (because of copying Q&A) and when redone with Safari, it went through OK with same set of Q&A
